# Generated by Django 3.0.7 on 2020-09-28 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
