# Generated by Django 3.0.7 on 2020-10-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201002_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='student',
            new_name='user',
        ),
    ]
