# Generated by Django 3.0.7 on 2020-09-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='file',
            name='sub_catagory',
        ),
        migrations.AddField(
            model_name='file',
            name='catagory1',
            field=models.CharField(blank=True, choices=[('Computer', 'Computer'), ('Electrical', 'Electrical'), ('Science', 'Science')], max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='catagory2',
            field=models.CharField(blank=True, choices=[('Logic', 'Logic'), ('Java', 'Java'), ('Empedded', 'Empedded'), ('Amplifier', 'Amplifier'), ('Antennas', 'Antennas'), ('Calculus', 'Calculus'), ('Chemistry 1', 'Chemistry 1')], max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='catagory3',
            field=models.CharField(blank=True, choices=[('Calculus 1', 'Calculus 1'), ('Calculus 2', 'Calculus 2'), ('Calculus 3', 'Calculus 3'), ('Java Lab', 'Java Lab'), ('Past Pappers', 'Past Pappers'), ('TextBooks', 'TextBooks')], max_length=100),
        ),
    ]
