# Generated by Django 3.0.7 on 2020-10-02 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0006_auto_20200930_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentFavorateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.File')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorate_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
